### ISSUE TITLE
Correct licence is "Expat"

### ISSUE THREAD

**Issue by htgoebel** [jamesturk/validictory#95]
MIT Licence is ambiguous. The correct name of the licence you are using is "Expat".
https://directory.fsf.org/wiki/License:Expat

Please correct this in setup.py. Thanks

**Comment by jamesturk** [comment]
This is the license the project uses.

https://opensource.org/licenses/MIT

**Comment by htgoebel** [comment]
MIT used different licences for differnet software, soe "MIT licence" is not clear enough. The one you are using is the "Expat" one.
Please read the comments here https://www.gnu.org/licenses/license-list.html#X11License
and here https://www.gnu.org/licenses/license-list.html#Expat

**Comment by paultag** [comment]
FWIW I mostly think "MIT" is a silly name (mostly because MIT actually uses BSD-3 most of the time), and "Expat" is slightly more right (so much so, that it's my default name for it), and in the latest version of the machine readable OSI data I have [both names in it](https://github.com/OpenSourceOrg/licenses/blob/master/licenses/manual/expat.json#L17-L26).

I mostly don't try to get people to change because it's a lot of energy for something that in the end is literally semantics
